### ISSUE TITLE
Can't disable

### ISSUE THREAD

**Issue by RickyTheSeaCat** [squgeim/yt-ad-autoskipper#12]
I've been using the autoskipper for a while and it's worked without any hiccups. The only issue I take with it is that there's no way to disable it if you see an ad that you want to watch, but you could always click the ad's video link to view it. If possible, adding a pause or stop feature for the skipper would be great, but I wouldn't prioritize it over fixing other issues.

Thanks!

**Comment by squgeim** [comment]
This has been added in the latest release (v2.0).

**Comment by squgeim** [comment]
This has been added in the latest release (v2.0).
