### ISSUE TITLE
Mute audio

### ISSUE THREAD

**Issue by slovak194** [squgeim/yt-ad-autoskipper#13]
Hi!

It would be nice to have audio muted out when add is playing playing.
And unmute it again after the add is closed.
Soundtrack of the add is usually more loud in comparison to the target video.

BR, Alex

**Comment by sbimochan** [comment]
Addressed in #14 however we may need to add an option to disable or enable this feature by users.

**Comment by squgeim** [comment]
This feature has been included in the latest release.

**Comment by squgeim** [comment]
This feature has been included in the latest release.
