### ISSUE TITLE
Does not work in miniplayer mode

### ISSUE THREAD

**Issue by PKCheap** [squgeim/yt-ad-autoskipper#19]
I know that this issue is because of the fact that your script mandates the '/watch' pathname, but is there a reason for this?

**Comment by PKCheap** [comment]
Update: 
I altered your script. Seems to work perfectly fine. 

#20

**Comment by squgeim** [comment]
The simple reason was that the mini-player mode did not exist back then so this was a sensible optimization. I will take a look at your pull request. Thanks!

**Comment by PKCheap** [comment]
Great! although my change now would really amount to taking a couple lines out. :P
