### ISSUE TITLE
Doesn't skip the new ads (white blank ads with a skip button when using adblocker)

### ISSUE THREAD

**Issue by L-m-b** [squgeim/yt-ad-autoskipper#30]
As the title says. new ads just play their 5 seconds through and i think with my Adblock it starts a second blank ad after the first finishes, but none after that.

**Comment by L-m-b** [comment]
![image](https://user-images.githubusercontent.com/30617839/93157697-0dd82400-f74e-11ea-9552-3a21aff854a9.png)

**Comment by towry** [comment]
It is true, it doesn't work.

**Comment by ravireddy07** [comment]
Now this also not happening for me....
Any other working things..?

**Comment by squgeim** [comment]
I have not been able to replicate this. Is this still happening?

**Comment by towry** [comment]
It seems working again.
