### ISSUE TITLE
Does not work with new Skip Ads box

### ISSUE THREAD

**Issue by thelewiss1** [squgeim/yt-ad-autoskipper#31]
Hello there, since very recently, the extension does not work anymore.
It seems to have coninsided with the new Skip Ads button, which looks like this.
![image](https://user-images.githubusercontent.com/40576482/94737624-06c42f00-0366-11eb-8adf-05c4d231f252.png)
![image](https://user-images.githubusercontent.com/40576482/94737635-0cba1000-0366-11eb-8d44-cb8e2bfb8f88.png)

`Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)
Windows 10 2004`

Thank you!

**Comment by bkjoel** [comment]
Next time this happens can you take a screenshot of the DOM focused on that btn? that way it could be tailored to that specific implementation of the "Skip ad" btn.

**Comment by thelewiss1** [comment]
Would you mind explaining how I’d do that?
I had a look, but wasn’t too sure
Thanks!

**Comment by bkjoel** [comment]
Sure, here's a few different ways to do it -
https://developers.google.com/web/tools/chrome-devtools/dom

**Comment by thelewiss1** [comment]
It's now started working? 
I'm not entirely sure why. I'll let you know if it happens again!
