### ISSUE TITLE
No longer working in Chrome as of today (11/3/2021)

### ISSUE THREAD

**Issue by richhosek** [squgeim/yt-ad-autoskipper#34]
Something must have changed on YouTube. The Extension is active in my browser, but ads are not being skipped.

**Comment by fusedevgithub** [comment]
me too

**Comment by Runflast** [comment]
Same Same. Since today (13.01.22). I live in Germany.

**Comment by johanessurya** [comment]
I have same issue yesterday and today.

**Comment by johanessurya** [comment]
> I have same issue yesterday and today.

I want to update what I experience today about this plugin. When I first open YT and ads show, it works. I don't know why. :)

**Comment by squgeim** [comment]
Thank you for letting me know. It looks like the recent change to YouTube, specifically the new feature to play a video by hovering on it, is causing this issue. I am working on a fix, will update soon.

**Comment by squgeim** [comment]
The issue only occurs if you hover and play a video. The extension works if you directly go to a video or refresh the video page.

**Comment by squgeim** [comment]
The extension has been updated with a fix in Chrome Web Store. It is under review in Firefox Addons Marketplace and Microsoft Store, they will be released shortly. You'll see this fixed in 0.5.1.
