### ISSUE TITLE
Stopped working again- very prominent complaints on Chrome Web Store

### ISSUE THREAD

**Issue by Ironwalk75** [squgeim/yt-ad-autoskipper#37]
Flat out not working for anyone as far as I'm aware - please fix, it is such a great item

**Comment by squgeim** [comment]
Thank you for letting me know. It looks like the recent change to YouTube, specifically the new feature to play a video by hovering on it, is causing this issue. I am working on a fix, will update soon.

**Comment by squgeim** [comment]
The extension has been updated with a fix in Chrome Web Store. It is under review in Firefox Addons Marketplace and Microsoft Store, they will be released shortly. You'll see this fixed in 0.5.1.

**Comment by Ironwalk75** [comment]
thank you so much!! :D
