### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AARP41298** [squgeim/yt-ad-autoskipper#38]
I will be aware of the updates

**Comment by squgeim** [comment]
Thank you for letting me know. It looks like the recent change to YouTube, specifically the new feature to play a video by hovering on it, is causing this issue. I am working on a fix, will update soon.

**Comment by squgeim** [comment]
The extension has been updated with a fix. You'll see this fixed in 0.5.1.

**Comment by AARP41298** [comment]
> The extension has been updated with a fix. You'll see this fixed in 0.5.1.

Thank you, everything works fine now
