### ISSUE TITLE
Ability to automatically mute ads (and unmute afterwards).

### ISSUE THREAD

**Issue by dejaime** [squgeim/yt-ad-autoskipper#4]
This would be a great addition to the extension. Muting ads would be great especially to avoid mood breaking songs, excessively loud ads, and would simply allow for a generally better experience.

**Comment by sbimochan** [comment]
Addressed in #14 however we may need to add an option to disable or enable this feature by users. Some other users may wanna listen to the ads too.

**Comment by squgeim** [comment]
This feature has been included in the latest release.

**Comment by squgeim** [comment]
This feature has been included in the latest release.
