### ISSUE TITLE
Not working on music.youtube.com

### ISSUE THREAD

**Issue by cloutierMat** [squgeim/yt-ad-autoskipper#41]
It would be great if it also worked on music.youtube.com, it appears the button uses the same classes as on youtube.com and `*://*.youtube.com/*` feels like it should match and skip the ads there too. I am stuck with the ads on music.youtube.

On google chrome, and it work as intended on youtube.com.

**Comment by agirorn** [comment]
Something must have changed since this used to work on music.youtube.com and now it does not. It would be really interesting to know what changed.

**Comment by cloutierMat** [comment]
I submitted a pull request that solves the issue.

The tag of the player is different. 
youtube: <ytd-player id="ytd-player"> 
music.youtube: <ytmusic-player id="player">

**Comment by squgeim** [comment]
Thanks for this! I had no idea it worked on YouTube music, I never tested it to work there. I'll incorporate the PR in the next update.

**Comment by squgeim** [comment]
This has been added in the latest release (v2.0).

**Comment by squgeim** [comment]
This has been added in the latest release (v2.0).

**Comment by eljose47** [comment]
It's once again not working for music.youtube.com
