### ISSUE TITLE
Outdated release in the Firefox Addon Marketplace

### ISSUE THREAD

**Issue by geisterfurz007** [squgeim/yt-ad-autoskipper#48]
I love this extension a lot! It seemed to have stopped working recently however so I thought I'd have a look at possible causes and first wanted to ensure I was on the most recent version.

The latest release in this repo is 2.0.0 however the last release made to the Firefox Addon Marketplace appears to be 0.5.1.

Is there any chance you could update the FF release of the addon?

**Comment by squgeim** [comment]
The new versions of the extension use Manifest v3 (as v2 has been deprecated on Chrome). Firefox, however, has not shipped support for v3 yet. I'll update the extension as soon as it is supported on Firefox.

**Comment by TenEXP** [comment]
It appears that the release on the Firefox Marketplace is [still outdated](https://github.com/squgeim/yt-ad-autoskipper) although Manifest V3 support was added to Firefox back in 109 according to [Extension Workshop](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/). If so, I believe this issue should be reopened.
