### ISSUE TITLE
Channel configure button missing

### ISSUE THREAD

**Issue by wblaircox** [squgeim/yt-ad-autoskipper#55]
I cannot get it to show the channel configure button after paying for the full version. 

![image](https://github.com/squgeim/yt-ad-autoskipper/assets/12896777/c5223a53-021b-491b-b649-644b32b181d0)

![image](https://github.com/squgeim/yt-ad-autoskipper/assets/12896777/e6a65ea9-fb6c-43fa-9bce-0b5d939a3515)

**Comment by squgeim** [comment]
Thanks for letting me know. Looks like a recent change to YouTube is breaking this. I'll push a fix soon.

**Comment by wblaircox** [comment]
No problem, love your app! Hope it lasts and YouTube doesn't kill it. I
kept the timer delay to 3 seconds. I feel like if enough people show up as
clicking the 'hidden' skip button before the 5 seconds, they'll go after a
fix for it. Might be tipping your hand by allowing us to trigger the skip
sooner.
