### ISSUE TITLE
[scam]"disable auto-renew" instead removed all options that i paid for

### ISSUE THREAD

**Issue by Layarion** [squgeim/yt-ad-autoskipper#58]
I bought the 1 year service, and 5 mins later seen that it doesn't actually skip the long ads even though it says it can, and decided i'll click the "disable auto renew" button so that i don't get charged again 1 year later.

what does it do? instead it immediately disables all the paid for options as well.

this motherfucking thing better be automatically doing a return as we speak.

**Comment by squgeim** [comment]
Hi @Layarion! Thank you for reaching out. I have started a refund for your payment. I was under the impression that the subscription would only cancel at the end of the period; I'll rectify that logic on my backend. Thank you for bringing this to my attention. As a thank you, I have applied a one-year subscription on your profile for free, with no future auto-renewal.

**Comment by squgeim** [comment]
Could you please let me know what kind of ads it was not able to skip? This extension only automates the action of skipping an ad, so ads that do not provide a "Skip Ad" button will not be skipped.

**Comment by Layarion** [comment]
> Could you please let me know what kind of ads it was not able to skip? This extension only automates the action of skipping an ad, so ads that do not provide a "Skip Ad" button will not be skipped.

ya it was one of the described "un-skippable ads" but i don't recall the text under the 5 second settings saying that was an exception, otherwise i wouldn't have bothered buying. honestly a short trial period of 7 days woulda been enough for me to figure out if the subscription would be something i'm interested in.

sorry for calling it a scam but i was pretty upset that the options grayed themselves out afterwards, if they hadn't i woulda just sucked up the 7 bucks and moved on.
