### ISSUE TITLE
Skipping does not work any more

### ISSUE THREAD

**Issue by synox** [squgeim/yt-ad-autoskipper#60]
Youtube changed it's skip button recently and automatic skipping does not work any more

**Comment by Ekipogh** [comment]
Same here. Seems that Youtube had an update

**Comment by squgeim** [comment]
Thanks for letting me know. Working on it.

**Comment by squgeim** [comment]
@synox @Ekipogh Hi! Could you please let me know which browser you use this extension on and what version of the extension you have? I have found that the version in Edge has stopped working but am unable to replicate the issue on the latest version on Chrome Web Store. The version on Edge store is behind because of a delay with their reviews.

**Comment by JocyW** [comment]
Can also confirm on Firefox:
Extension version: 0.5.1 
Firefox version: 119.0 

Coincided with a UI change on Youtube:
<img width="139" alt="image" src="https://github.com/squgeim/yt-ad-autoskipper/assets/16762967/d9276568-9a80-4749-b532-857159de84f3">

**Comment by SQKo** [comment]
The button class has been changed to `ytp-ad-skip-button-modern ytp-button`

**Comment by Ekipogh** [comment]
Extension: 0.5.1
Firefox: 119.0.1

**Comment by synox** [comment]
Firefox: 120.0b9 (64-bit)
Extension: 0.5.1

**Comment by squgeim** [comment]
Thanks.

Firefox is a few versions behind because they did not support manifest v3 when I ported the extension over. They now support it but there are differences from Chrome that needs to be accounted for.

I'll push a fix for Firefox with manifest v2 later today.

**Comment by squgeim** [comment]
Firefox add-on has been updated. Please update to `0.5.2`. An update for Edge will be out as soon as their review is done.

**Comment by synox** [comment]
Thanks this seems to work.

**Comment by nm004** [comment]
Thank you. It works (Firefox 119.0 (64-bit)).

**Comment by Ekipogh** [comment]
Updated the extension. Works now. Thank you.
