### ISSUE TITLE
extension stops working after some time

### ISSUE THREAD

**Issue by janvarga94** [squgeim/yt-ad-autoskipper#61]
using firefox, at first it works but it wears off for some reason

**Comment by Memeruf** [comment]
Likewise - mine stopped working today after less than a month.

**Comment by simonik** [comment]
The same problem.

**Comment by benmarten** [comment]
Same. It seems Firefox disables the extensions? See how two of my extensions are grayed out, although they are enabled...
<img width="401" alt="Screenshot 2024-03-23 at 8 39 23 PM" src="https://github.com/squgeim/yt-ad-autoskipper/assets/5960238/126fa4a1-3199-4550-86a4-aa937cc13fa3">

**Comment by Ekipogh** [comment]
Same. The extension is greyed out.

**Comment by squgeim** [comment]
I am sorry, but I have been unable to replicate the extension not working in Firefox. Could you please make a note of what kind of ad it was when it does not work? Ads with a skip button should work.

About the extension being greyed out, that is unrelated. The extension only requests access for YouTube, so it is rightly greyed out when you are on any other site. When you are on YouTube, it should say "can always read and change data on this site".

**Comment by Ekipogh** [comment]
Here is a screenshot of extension being grey out on youtube. 
![image](https://github.com/squgeim/yt-ad-autoskipper/assets/3126903/3e775256-b13f-45ce-b7f6-88abc862bea1)

**Comment by squgeim** [comment]
> Here is a screenshot of extension being grey out on youtube. 
> 
> ![image](https://github.com/squgeim/yt-ad-autoskipper/assets/3126903/3e775256-b13f-45ce-b7f6-88abc862bea1)
> 
> 

Thanks @Ekipogh. This looks right to me. The extension is greyed out because there is no click action there. It correctly says the extension can read and change data on this site.

**Comment by squgeim** [comment]
A fix for recent Youtube changes has been released. Please note that the greyed out look is normal. It is going through Chrome review and will go out as soon as that's done. Please look out for version 2.0.2.
