### ISSUE TITLE
Cancel subscription

### ISSUE THREAD

**Issue by 0Sanjiu** [squgeim/yt-ad-autoskipper#62]
I want to cancel my subscription but can't find an option. Then, I removed the extension but was still charged for another year.

**Comment by squgeim** [comment]
I am sorry to here that. The link to cancel can be found in the extension's preferences page which can be opened by clicking on the extension icon in your browser's extensions list.

I will cancel the subscription on my end and refund your last payment. Could you please email me at shreyadahal@gmail.com from the email address associated with the payment?
