### ISSUE TITLE
Not skipping the ads

### ISSUE THREAD

**Issue by Stayca1m** [squgeim/yt-ad-autoskipper#65]
So when I'm watching youtube a ads pop up it is supposed to skip after 5 seconds but it doesn't the ad is still there please fix it. I'm using Chrome, the app version is 2.0.1 also but it won't auto-skip the ad for me.

**Comment by Stayca1m** [comment]
Here's a picture of it
![image](https://github.com/squgeim/yt-ad-autoskipper/assets/157792955/668b8127-6a7e-46a6-b56e-ac96f0217389)

**Comment by Stayca1m** [comment]
For some reason it's worked now ig you guys updated it ty alot

**Comment by squgeim** [comment]
hi @Stayca1m! I'm glad it sorted itself out. It could be Youtube testing something. Sometimes just restarting the browser can help as well.
