### ISSUE TITLE
Intermittent performance and/or not working as of week of 15 April 2024

### ISSUE THREAD

**Issue by cverges-medallia** [squgeim/yt-ad-autoskipper#67]
Starting 15 April 2024 or so, YouTube appears to have made some kind of change that now makes the extension not fully work.  There's an increased number of ads where the Skip button shows, but the Extension doesn't click it for some reason.  Pasting what from the DOM I could gather on the last one in case it helps.

![Screenshot 2024-04-17 at 10 58 30 AM](https://github.com/squgeim/yt-ad-autoskipper/assets/13562488/8c85a466-d8d5-4efd-a930-3d124551d82c)

**Comment by FajnB** [comment]
Can confirm that somewhere around 15th of April, google have once again done something to prevent people auto skip ads.

**Comment by ihave1000usernames** [comment]
I didn't notice an issue until today, the 18th of April. I watch YT on and off all day, every day. I'm running Chrome Version 123.0.6312.122 (Official Build) (64-bit) on Linux Mint. Flathub from stable branch com.google.Chrome.

**Comment by squgeim** [comment]
Thanks everyone. I am trying to figure out what has changed.

**Comment by squgeim** [comment]
A fix for this has been released. It is going through Chrome review and will go out as soon as that's done. Please look out for version 2.0.2.

**Comment by FajnB** [comment]
When will this fix be available on Firefox?
Or did you discontinued it there? (_Genuinely asking as it kinda looks like I'm complaining._)

**Comment by squgeim** [comment]
> When will this fix be available on Firefox?
> 
> Or did you discontinued it there? (_Genuinely asking as it kinda looks like I'm complaining._)

Hi! The fix will be available as version 0.5.3 on Firefox. It is still in review. Usually Firefox review is quicker than Chrome's but this time it has been stuck at Awaiting Review for the last few days.

**Comment by cverges-medallia** [comment]
FYI, upon further testing this week, it looks like this fix is working ~70% of the time.  I'm still seeing some ads where the Skip button shows but isn't getting clicked by the extension.

DOM snapshot during the latest one that I could capture:
![Screenshot 2024-04-25 at 2 45 20 PM](https://github.com/squgeim/yt-ad-autoskipper/assets/13562488/44d38896-63f6-415d-8cab-1480a8aece2a)

**Comment by FajnB** [comment]
Can confirm, that the extension (Firefox 0,5,3) is working, but sometimes it does not. In my experience is the success rate is somewhere between 80-90%.

Youtube is changing its design yet again in the last two months so there could be a possibility that they are doing some sort of test of several possible designs.
Also google have apparently upped their effort in persecution of people using ad-blockers. This might also come with side effects like changing the way the skip button works.
