### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by cowls192** [squgeim/yt-ad-autoskipper#69]
I guess its that time for routine code fix. The extension is not working as of 2024 Apr 22, and im confident all you have to do is update some codes to make it work.

I dont know if you are aware but plenty of users are also complaining about extension not working recently, and i wish i didnt have to visit this website to report such quick fix. At least check Chrome Web Store reviews for user feedbacks or make it easier to report such issues on Extension options page.

Also, im wondering why subscription is not available for Firefox version.

Windows 11 Home 23H2 OS Build 22631.3447
Chrome Version 124.0.6367.61 (Official Build) (64-bit)

**Comment by squgeim** [comment]
Hi @cowls192! I pushed out a fix today. It is in review by Chrome and will be out as soon as they are done with it.
