### ISSUE TITLE
Automatically to close the little ad in the bottom of the video

### ISSUE THREAD

**Issue by gkkirilov** [squgeim/yt-ad-autoskipper#7]

**Comment by squgeim** [comment]
Could you please elaborate what you mean by this?

**Comment by gkkirilov** [comment]
Hi I have attached a screenshot of the ad ![example](https://user-images.githubusercontent.com/8720012/42516499-c03377ba-8466-11e8-95ca-9120ec4be1cd.png)

**Comment by squgeim** [comment]
This has been implemented and released in the latest version.
