### ISSUE TITLE
Skip not triggering under certain conditions

### ISSUE THREAD

**Issue by cverges-medallia** [squgeim/yt-ad-autoskipper#70]
Using latest Chrome with the extension version 2.0.2.  That fixed some of the skip problems, but I'm still seeing others intermittently.

I haven't been able to capture the actual issue, but it's almost like YouTube is starting to play an add, then it moves to a different add less than half a second later.  If I'm able to capture it, I'll add more info.

**Comment by squgeim** [comment]
Hi! I am aware of the recent changes in Youtube am an trying to find a work around. Continued discussion in #77.
