### ISSUE TITLE
Unable to sign into the Chrome Extension 

### ISSUE THREAD

**Issue by Cole-Trickle75** [squgeim/yt-ad-autoskipper#76]
Hello There 

For some reason I can't sign into the Chrome Extension. When I click on the Sign into account button it seems to refresh quickly then the button comes back and I can't sign in. Tried clearing Cache, restarting the browser. signing out and signing back in again. Removed and re-added the extension from the profile as well. It happened when I started a second profile on my work computer for more personal items and the Extension was signed in fine on the original profile but wouldn't sign in again in the new profile.

**Comment by Cole-Trickle75** [comment]
To add: I was on an auto renew but could it be my payment didn't renew?

**Comment by squgeim** [comment]
Hey Cole! I will take a look at what's happening. I'll let you know by tomorrow.

**Comment by Cole-Trickle75** [comment]
Fantastic thank you.

~Greg

**Comment by squgeim** [comment]
This is an issue with Firebase Auth SDK I use for authentication. I am working on upgrading it the latest version. I will have it fixed in a few days.

**Comment by squgeim** [comment]
@Cole-Trickle75 Hi! Please try again now. It should be fixed now.

**Comment by Cole-Trickle75** [comment]
Hi Shreya
 Sounds great thank you ! I won't be able to test until Tuesday.
Taking a vacation day tomorrow

**Comment by Cole-Trickle75** [comment]
Hi Sherea

My apologies for not getting back to you sooner. I've been running the app
for a few days now and it's flawless once more.

Thanks for all your expertise and assistance when changes are required.

The app is fantastic in my opinion.

Thank you again!

Greg Cole, MCP, A+
Calgary AB

"When emotion brings us ghosts from the past, only logic can root us in the
present" - SAREK - "THE VULCAN HELLO"
