### ISSUE TITLE
Basic skip function has stopped working in some cases

### ISSUE THREAD

**Issue by nicholas-eden** [squgeim/yt-ad-autoskipper#78]
It looks like they changed the skip button behavior a bit.  The plugin is working for some ads, but not others.  I think they hide the skip button until after the ad and are detecting if the click comes first.

**Comment by squgeim** [comment]
Thanks! I have been seeing some reports of it not working but haven't been able to verify. This could be it.

**Comment by nicholas-eden** [comment]
Is anyone else having this issue?  Its not skipping at all for me anymore.

**Comment by squgeim** [comment]
Hey! The new UI update finally made it to me and I have fixed it. It will be released after review by Chrome and Edge.
