### ISSUE TITLE
Skip feature not working at all

### ISSUE THREAD

**Issue by Jaden-Allen** [squgeim/yt-ad-autoskipper#80]
Youtube somewhat recently updated the skip button to only display after about 5 seconds, there is no longer a countdown. I believe this has something to do with the break, maybe im the only one with this new design of ads but its happened consistently with every skippable ad for atleast 2 weeks now. It also might even be slightly longer than 5 seconds now as the buttons transparency fades to opaque after what i believe would be 5 seconds.

**Comment by squgeim** [comment]
Hey! The new UI update finally made it to me and I have fixed it. It will be released after review by Chrome and Edge.
