### ISSUE TITLE
nothing working

### ISSUE THREAD

**Issue by roxiemic** [squgeim/yt-ad-autoskipper#81]
for the past two days nothing is working its not even muting the ads

**Comment by riccardosimo** [comment]
Same here :(

**Comment by nicholas-eden** [comment]
Yeah, I think the the author got tired of YouTube constantly changing things to break plugins like this.

**Comment by squgeim** [comment]
> Yeah, I think the the author got tired of YouTube constantly changing things to break plugins like this.

Ha. Not really. I use it all the time. Unfortunately, I can't do anything until it's consistently breaking for me. :(

**Comment by bttruman** [comment]
Hi @squgeim, I would like to report the same. Audio is not muted anymore during ads, and they do not automatically skip after a few seconds. Using Brave v 1.71.118, if that's helpful.

**Comment by russellsilva** [comment]
The extension stopped working for me today too. I'm in Portland, Oregon using Chrome on Windows.

**Comment by squgeim** [comment]
Hey guys! The new UI update finally made it to me and I have fixed it. It will be released after review by Chrome and Edge.
