### ISSUE TITLE
Plugin No Longer Working After UI Change

### ISSUE THREAD

**Issue by bttruman** [squgeim/yt-ad-autoskipper#82]
Hey there,

Would like to report that the plugin is no longer functional after a recent YouTube UI change that happened about a week ago. There’s no longer a countdown on the Skip button, and instead there’s a yellow bar at the bottom of the video that indicates the amount of time left on the ad. Once it moves fully from left to right, then the Skip button appears. 

Additionally, the automatic mute toggle does not work. Ads are not automatically muted, and if you mute them manually the video is not automatically unmuted once the Ad is skipped (Not sure if that was a function of the plugin before or not, but something I tested). 

Please, squgeim-kenobi, you’re our only hope!

**Comment by squgeim** [comment]
Thank you for the detailed report. Unfortunately the new UI has not made it to my system yet. Still waiting.

I promise to make it work as soon as I can replicate it.

**Comment by viteo** [comment]
not sure, but they've added Event Listner for Skip button that checks is this click event isTrusted or some more sofisticated parameters. so simple dispatchEvent with 'click' doesn't trigger the button any more. looks like we need a way to bypass this check.

**Comment by squgeim** [comment]
> not sure, but they've added Event Listner for Skip button that checks is this click event isTrusted or some more sofisticated parameters. so simple dispatchEvent with 'click' doesn't trigger the button any more. looks like we need a way to bypass this check.

I have already worked around that in the previous version. I think this time it's just a UI change.

**Comment by squgeim** [comment]
Hey guys! The new UI update finally made it to me and I have fixed it. It will be released after review by Chrome and Edge.

**Comment by russellsilva** [comment]
Thanks as always for your work on this extension, @squgeim. It really is a pleasure to use.
