### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by sabujp** [squgeim/yt-ad-autoskipper#9]
Google Chrome	70.0.3538.16 (Official Build) beta (64-bit)
Revision	16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS	Linux

turned off all other adblock extensions (ublock, adblock, tampermonkey)

**Comment by Gani-D** [comment]
sorry, just wanted to say that this addon is amazing!
Great job!

**Comment by squgeim** [comment]
@Gani-D Thank you! You can always contribute to make it even better!

**Comment by squgeim** [comment]
@sabujp I don't seem to have the same issue and I do not see any other complaints. Could you check if it still does not work (there have been updates since you raised the issue)? If not I'll close this issue.

**Comment by bzero** [comment]
works for me too, after install need to restart YouTube page only, great work ;)
